const getIconClassBasedOnExtension = (fileExtension) => {
    const iconClass = "far fa-file-";
    switch (fileExtension) {
        case "pdf":
        case "fdf":
        case "apf":
        case "pdx":
        case "dwf":
        case "acrob":
        case "acrop":
            return `${iconClass}pdf`;
        case "xls":
        case "xlt":
        case "xltx":
        case "xlsx":
        case "xlsm":
        case "xltm":
        case "xlm":
        case "xlsb":
        case "xlsa":
        case "xlsam":
        case "xll":
        case "xlw":
            return `${iconClass}excel`;
        case "doc":
        case "docx":
        case "docm":
        case "dotx":
        case "dotm":
        case "docb":
        case "wbk":
            return `${iconClass}word`;
        case "ppt":
        case "pot":
        case "pps":
        case "pptx":
        case "pptm":
        case "potx":
        case "potm":
        case "ppam":
        case "ppsx":
        case "ppsm":
        case "pldx":
        case "sldm":
            return `${iconClass}powerpoint`;
        case "jpg":
        case "jpeg":
        case "png":
        case "gif":
        case "tiff":
            return `${iconClass}image`;
        case "asp":
        case "css":
        case "html":
        case "xml":
        case "js":
        case "jsx":
        case "php":
        case "jsp":
        case "jspx":
        case "yaml":
        case "yml":
            return `${iconClass}code`;
        case "zip":
        case "rar":
        case "gz":
        case "tar":
        case "7z":
        case "arj":
        case "deb":
        case "pkg":
        case "rpm":
        case "tar.gz":
        case "z":
            return `${iconClass}archive`;
        case "m4a":
        case "flac":
        case "mp3":
        case "wav":
        case "wma":
        case "aac":
        case "aif":
        case "cda":
        case "mpa":
        case "ogg":
        case "wpl":
            return `${iconClass}audio`;
        case "mp4":
        case "mov":
        case "wmv":
        case "flv":
        case "avi":
        case "avchd":
        case "webm":
        case "mkv":
        case "3g2":
        case "3gp":
        case "h264":
        case "m4v":
        case "mpg":
        case "mpeg":
        case "rm":
        case "vob":
            return `${iconClass}video`;
        default:
            return `${iconClass}alt`;
    }
};

export default getIconClassBasedOnExtension;
